dash/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.home, name='home'),
    path('update/<int:pk>', views.edit_service, name="edit_service"),
    path('change_password', views.change_password, name='change'),
    path('signup', views.Admin_signup_view, name='signup'),
    path('asset/', views.asset, name='asset'),
    path('edit/<int:pk>', views.edit_asset, name="edit_asset"),
    path('delete/<int:pk>', views.delete_asset, name="delete_asset"),
]

sss/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashboard/', include('dash.urls')),
    path('login/', views.login_user, name='Login'),
    path('logout/', views.logout_user, name='Logout'),
    path('afterlogin', views.afterlogin_view, name='afterlogin'),
    path('service/', views.customer_view, name='customer'),
    path('save', views.save, name='save')
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/include/footer.html
<footer class="footer py-4  ">
    <div class="container-fluid">
        <div class="row align-items-center justify-content-lg-between">
            <div class="col-lg-6 mb-lg-0 mb-4">
                <div class="copyright text-center text-xl  text-lg-start text-dark ">
                    ©
                    <script>
                        document.write(new Date().getFullYear())
                    </script>&nbsp;
                    Developed and maintained by
                    <a href="{% url 'dashboard:home' %}" class="font-weight-bolder" target="_blank">SSS SOLUTIONS</a>.
                </div>
            </div>

        </div>
    </div>
</footer>

templates/include/login_foooter.html
<footer class="footer position-absolute bottom-2 py-2 w-100">
    <div class="container">
        <div class="row align-items-center justify-content-lg-between">
            <div class="col-12 col-md-6 my-auto">
                <div class="copyright text-center text-sm text-white text-lg-start">
                    ©
                    <script>
                        document.write(new Date().getFullYear())
                    </script>&nbsp;
                    Developed and maintained by
                    <a href="{% url 'dashboard:home' %}" class="font-weight-bolder text-white" target="_blank">SSS SOLUTIONS</a>.
                </div>
            </div>

        </div>
    </div>
</footer>

templates/include/navbar.html
{% load static %}
<aside class="sidenav navbar navbar-vertical navbar-expand-xs border-0 border-radius-xl my-3 fixed-start ms-3 bg-white"
       id="sidenav-main">
    <div class="sidenav-header">
        <i class="fas fa-times p-3 cursor-pointer text-white opacity-5 position-absolute end-0 top-0 d-none d-xl-none"
           aria-hidden="true" id="iconSidenav"></i>
        <a class="navbar-brand m-0" href="/" target="_blank">
            <!--- <img src="../assets/img/logo-ct.png" class="navbar-brand-img h-100" alt="main_logo"> -->
            <span class="ms-1 font-weight-bolder text-dark">Admin Dashboard</span>
        </a>
    </div>
    <hr class="horizontal light mt-0 mb-2">
    <div class="collapse navbar-collapse  w-auto " id="sidenav-collapse-main">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link text-dark {% if request.path == '/dashboard/' %}active bg-gradient-info{% endif %}"
                   href="#" onclick="showLoading(event, '{% url 'dashboard:home' %}')">
                    <div class="text-dark text-center me-2 d-flex align-items-center justify-content-center">
                        <i class="material-icons opacity-10">dashboard</i>
                    </div>
                    <span class="nav-link-text ms-1">Dashboard</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-dark {% if request.path == '/dashboard/asset/' %}active bg-gradient-info{% endif %}"
                   href="#" onclick="showLoading(event, '{% url 'dashboard:asset' %}')">
                    <div class="text-dark text-center me-2 d-flex align-items-center justify-content-center">
                        <i class="material-icons opacity-10">dvr</i>
                    </div>
                    <span class="nav-link-text ms-1">Asset</span>
                </a>
            </li>
        </ul>
    </div>
</aside>