sss/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashboard/', include('dash.urls')),
    path('login/', views.login_user, name='Login'),
    path('logout/', views.logout_user, name='Logout'),
    path('afterlogin', views.afterlogin_view, name='afterlogin'),
    path('service/', views.customer_view, name='customer'),
    path('save', views.save, name='save')
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dash/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Admin(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    address = models.CharField(max_length=50, null=False, blank=False)
    is_Active = models.BooleanField(default=True)

    @property
    def get_name(self):
        return self.user.first_name + " " + self.user.last_name

    @property
    def get_instance(self):
        return self

    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name_plural = "Admin"

user/models.py
from django.db import models


# Create your models here.

class branch_user(models.Model):
    user = models.CharField(max_length=50, null=True, blank=True)
    branch = models.ForeignKey('utility.branch', on_delete=models.SET_NULL, blank=False, null=True)
    pc = models.ForeignKey('utility.device_list', on_delete=models.SET_NULL, blank=False, null=True)

templates/customer/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Service Dashboard</title>
    <!--     Fonts and icons     -->
    <link rel="stylesheet" type="text/css"
          href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,900|Roboto+Slab:400,700"/>

    <!-- Material Icons -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons+Round" rel="stylesheet">

    <!-- Font Awesome Icons -->
    <script src="https://kit.fontawesome.com/4933fc35b1.js" crossorigin="anonymous"></script>

    <!-- CSS Files -->
    <link id="pagestyle" href="{% static 'css/material-dashboard.css' %}" rel="stylesheet"/>
<style>
    #loading {
    position: fixed;
    z-index: 9999;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    background-color: rgba(0, 0, 0, 0.5);
    display: flex;
    justify-content: center;
    align-items: center;
}

#loading img {
    width: 100px;
    height: 100px;
    object-fit: contain;
    display: block;
    margin: auto;
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
}
</style>
    {% block css %}{% endblock css %}
</head>
<body class="g-sidenav-show  bg-gray-200">
<main class="main-content position-relative max-height-vh-100 h-100 border-radius-lg ">
    <div id="loading" style="display:none;">
        <!-- your loading animation code here -->
        <img src="{% static 'img/loading.gif' %}" alt="loading">
    </div>
    {% block content %}

    {% endblock %}

</main>
</body>
<!--   Core JS Files   -->
<script src="{% static 'js/core/popper.min.js' %}"></script>
<script src="{% static 'js/core/bootstrap.min.js' %}"></script>
<script src="{% static 'js/plugins/perfect-scrollbar.min.js' %}"></script>
<script src="{% static 'js/plugins/smooth-scrollbar.min.js' %}"></script>
<script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>

{% block js %}{% endblock js %}
<script>
    var win = navigator.platform.indexOf('Win') > -1;
    if (win && document.querySelector('#sidenav-scrollbar')) {
        var options = {
            damping: '0.5'
        }
        Scrollbar.init(document.querySelector('#sidenav-scrollbar'), options);
    }
</script>
<!-- Github buttons -->
<script async defer src="https://buttons.github.io/buttons.js"></script>
<!-- Control Center for Material Dashboard: parallax effects, scripts for the example pages etc -->
<script src="{% static 'js/material-dashboard.js' %}"></script>


</html>

templates/customer/login.html
{% extends 'login_base.html' %}
{% load static %}
{% block css %}
    <style>
        #loading {
            position: fixed;
            z-index: 9999;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            background-color: rgba(0, 0, 0, 0.5);
            display: flex;
            justify-content: center;
            align-items: center;
        }

        #loading img {
            width: 100px;
            height: 100px;
            object-fit: contain;
        }
    </style>
{% endblock css %}
{% block content %}
    <div class="page-header align-items-start min-vh-100"
         style="background-image: url('https://images.unsplash.com/photo-1497294815431-9365093b7331?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1950&q=80');">
        <span class="mask bg-gradient-dark opacity-6"></span>
        <div class="container my-auto">
            <div class="row">
                <div id="loading" style="display:none;">
                    <!-- your loading animation code here -->
                    <img src="{% static 'img/loading.gif' %}" alt="loading">
                </div>
                <div class="col-lg-4 col-md-8 col-12 mx-auto">
                    <div class="card z-index-0 fadeIn3 fadeInBottom">
                        <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
                            <div class="bg-gradient-info shadow-primary border-radius-lg py-3 pe-1">
                                <h4 class="text-white font-weight-bolder text-center mt-2 mb-0">Sign in</h4>
                            </div>
                        </div>
                        <div class="card-body">
                            <form action="{% url 'customer' %}" method="post" role="form" class="text-start">
                                {% csrf_token %}
                                <div class="input-group input-group-outline my-3">
                                    <label class="form-label" for="username">UserName</label>
                                    <input name="username" id="username" class="form-control" required>
                                </div>
                                <div class="input-group input-group-outline my-3">
                                    <select class="form-control" id="branch" name="branch">
                                        <option value="" selected>Select a branch</option>
                                        {% for d in br %}
                                            <option value="{{ d.id }}">{{ d }}</option>
                                        {% endfor %}
                                    </select>
                                </div>


                                <div class="text-center">
                                    <button type="submit" class="btn bg-gradient-info w-100 my-4 mb-2" value="Login">
                                        Log in
                                    </button>
                                </div>

                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
{% endblock %}
{% block js %}
    <script>
        {% if messages %}
            {% for message in messages %}
                Swal.fire({
                    icon: '{{ message.tags }}',
                    title: '{{ message }}'
                });
            {% endfor %}
        {% endif %}

        $(document).ready(function () {
            $('form').submit(function () {
                $('#loading').show();
            });
        });
    </script>
{% endblock %}

templates/customer/service.html
{% extends 'customer/base.html' %}
{% load static %}
{% load widget_tweaks %}
{% block css %}
    <style>
        .fixed-button {
            position: fixed;
            bottom: 35px;
            right: 30px;
            z-index: 9999;
            width: 75px; /* Adjust the width */
            height: 70px; /* Adjust the height */
            border-radius: 15px; /* Half of the height to create an oval shape */
            display: flex;
            justify-content: center;
            align-items: center;
        }
    </style>
{% endblock %}

{% block content %}
    <!-- Navbar -->
    <nav class="navbar navbar-main navbar-expand-lg px-0 mx-4 shadow-none border-radius-xl" id="navbarBlur"
         data-scroll="true">
        <div class="container-fluid py-1 px-3">
            <nav aria-label="breadcrumb">
                <img src="{% static 'img/logo.png' %}" class="navbar-brand-img h-100" width="150" alt="main_logo">

            </nav>
            <div class="collapse navbar-collapse mt-sm-0 mt-2 me-md-0 me-sm-4" id="navbar">
                <div class="ms-md-auto pe-md-3 d-flex align-items-center"></div>
                <ul class="navbar-nav  justify-content-end">
                    <li class="nav-item d-flex align-items-center text-dark">
                        <span class="d-sm-inline d-none text-xl"><span
                                class="text-success">Welcome!</span>&nbsp;{{ user.username }}</span>
                    </li>
                    &nbsp;&nbsp;

                </ul>
            </div>
        </div>
    </nav>

    <!-- End Navbar -->
    <div class="container-fluid py-4">
        <div class="row">
            {% for i in ser %}
                <div class="col-xl-2 col-sm-6 mb-xl-3 mb-4">
                    <div class="card" style="background-color: #DFE0DF">
                        <div class="card-header p-3 pt-2" style="background-color: #DFE0DF">
                            <div class="pt-1 text-center" style="background-color: #DFE0DF">
                                <h4 class="text-xl mb-0 text-capitalize text-dark">{{ i.user }}</h4>
                                <h5 class="mb-0 text-dark">{{ i.branch }}</h5>

                                <h6 class="mb-0 text-dark"> {{ i.issue }}</h6>
                            </div>
                        </div>
                        <hr class="horizontal my-0">


                    </div>
                </div>
            {% endfor %}
        </div>
        <a href="#" class="btn btn-info rounded-circle fixed-button" data-bs-toggle="modal"
           data-bs-target="#modal-form">
            <i class="material-icons opacity-10" style="font-size:35px;">add</i>
        </a>

    </div>

    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
         aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title font-weight-normal" id="exampleModalLabel">Modal title</h5>
                    <button type="button" class="btn-close text-dark" data-bs-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    ...
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn bg-gradient-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="button" class="btn bg-gradient-primary">Save changes</button>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="modal-form" tabindex="-1" role="dialog" aria-labelledby="modal-form" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered modal-sm" role="document">
            <div class="modal-content">
                <div class="modal-body p-0">
                    <div class="card card-plain">
                        <div class="card-header pb-0 text-left">

                        </div>
                        <div class="card-body">

                            <form role="form text-left" id="form" method="post" action="">
                                {% csrf_token %}
                                <input type="hidden" name="user" maxlength="50" value="{{ ad.sys_name }}" class="form-control" id="id_user">
                                <input type="hidden" name="branch" class="form-control" required="" id="id_branch" value="{{ ad.branch.id }}">
                                <input type="hidden" name="pc" value="{{ ad.id }}" id="id_pc">
                                <div class="input-group input-group-static my-3">
                                    <label>Issue:</label>
                                    {% render_field form.issue class="form-control" name="Route" %}
                                </div>
                                <div class="text-center">
                                    <button type="submit" class="btn btn-round bg-gradient-info btn-lg w-100 mt-4 mb-0">
                                        Submit
                                    </button>
                                </div>
                            </form>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block js %}
    <script src="{% static 'js/plugins/sweetalert2@11.js' %}"></script>
    <script>
        function showLoading(event, url) {
            // Prevent the default behavior of the hyperlink
            event.preventDefault();

            // Display the loading animation
            document.getElementById("loading").style.display = "block";

            // Redirect to the URL after a 1-second delay
            setTimeout(function () {
                window.location.href = url;
            }, 1000);
        }
    </script>

    <script>
        $('form').submit(function (event) {
            event.preventDefault();
            $.ajax({
                url: '{% url 'save' %}',
                type: 'POST',
                data: $('form').serialize(),
                success: function (response) {
                    if (response.success) {
                        // Display success message using SweetAlert
                        Swal.fire({
                            icon: 'success',
                            title: 'Success',
                            text: response.message,
                            showConfirmButton: false,
                            timer: 1000
                        })
                    } else {
                        // Display error message using SweetAlert
                        Swal.fire({
                            icon: 'error',
                            title: 'Error',
                            text: response.message,
                            showConfirmButton: false,
                            timer: 1000
                        });
                    }
                },
                error: function (xhr, status, error) {
                    console.log(xhr.responseText);
                    // Display error message using SweetAlert
                    Swal.fire({
                        icon: 'error',
                        title: 'Error',
                        text: 'An error occurred. Please try again later.',
                        showConfirmButton: false,
                        timer: 1000
                    });
                },
                complete: function () {
                    // Hide the loading image
                    $('#loading').hide();
                }
            });
        });

        $(document).ready(function () {
            $('form').submit(function () {
                // Show the loading image
                $('#loading').show();
            });
        });
    </script>
{% endblock %}