dash/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.home, name='home'),
    path('update/<int:pk>', views.edit_service, name="edit_service"),
    path('change_password', views.change_password, name='change'),
    path('signup', views.Admin_signup_view, name='signup'),
    path('asset/', views.asset, name='asset'),
    path('edit/<int:pk>', views.edit_asset, name="edit_asset"),
    path('delete/<int:pk>', views.delete_asset, name="delete_asset"),
]

sss/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashboard/', include('dash.urls')),
    path('login/', views.login_user, name='Login'),
    path('logout/', views.logout_user, name='Logout'),
    path('afterlogin', views.afterlogin_view, name='afterlogin'),
    path('service/', views.customer_view, name='customer'),
    path('save', views.save, name='save')
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Admin Dashboard</title>
    <!--     Fonts and icons     -->
    <link rel="stylesheet" type="text/css"
          href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,900|Roboto+Slab:400,700"/>

    <!-- Material Icons -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons+Round" rel="stylesheet">

    <!-- Font Awesome Icons -->
    <script src="https://kit.fontawesome.com/4933fc35b1.js" crossorigin="anonymous"></script>

    <!-- CSS Files -->
    <link id="pagestyle" href="{% static 'css/material-dashboard.css' %}" rel="stylesheet"/>
<style>
    #loading {
    position: fixed;
    z-index: 9999;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    background-color: rgba(0, 0, 0, 0.5);
    display: flex;
    justify-content: center;
    align-items: center;
}

#loading img {
    width: 100px;
    height: 100px;
    object-fit: contain;
    display: block;
    margin: auto;
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
}
</style>
    {% block css %}{% endblock css %}
</head>
<body class="g-sidenav-show  bg-gray-200">
{% include 'include/navbar.html' %}
<main class="main-content position-relative max-height-vh-100 h-100 border-radius-lg ">
    <div id="loading" style="display:none;">
        <!-- your loading animation code here -->
        <img src="{% static 'img/loading.gif' %}" alt="loading">
    </div>
    {% block content %}

    {% endblock %}
    {% include 'include/footer.html' %}

</main>
</body>
<!--   Core JS Files   -->
<script src="{% static 'js/core/popper.min.js' %}"></script>
<script src="{% static 'js/core/bootstrap.min.js' %}"></script>
<script src="{% static 'js/plugins/perfect-scrollbar.min.js' %}"></script>
<script src="{% static 'js/plugins/smooth-scrollbar.min.js' %}"></script>
<script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>

{% block js %}{% endblock js %}
<script>
    var win = navigator.platform.indexOf('Win') > -1;
    if (win && document.querySelector('#sidenav-scrollbar')) {
        var options = {
            damping: '0.5'
        }
        Scrollbar.init(document.querySelector('#sidenav-scrollbar'), options);
    }
</script>
<!-- Github buttons -->
<script async defer src="https://buttons.github.io/buttons.js"></script>
<!-- Control Center for Material Dashboard: parallax effects, scripts for the example pages etc -->
<script src="{% static 'js/material-dashboard.js' %}"></script>


</html>

templates/change_password.html
{% extends 'base.html' %}

{% block content %}
    <div class="container-fluid py-4 al">
        <div class="row mb-4">
            <div class="col-lg-6 col-md-6 mb-md-0 mb-4 scroll mx-auto">
                <div class="card">
                    <div class="card-header pb-0">
                        <h2>Change Password</h2>
                    </div>
                    <div class="card-body px-0 pb-2">
                        <form method="post" class="mx-auto">
                            {% csrf_token %}
                            <div class="input-group input-group-outline my-3 px-4">
                                <label class="form-label" for="id_old_password">Old password</label>
                                <input type="password" name="old_password" autocomplete="current-password" autofocus
                                       required id="id_old_password" class="form-control">
                            </div>
                            <div class="input-group input-group-outline my-3 px-4">
                                <label class="form-label" for="id_new_password1">New password</label>
                                <input type="password" name="new_password1" autocomplete="new-password" required
                                       id="id_new_password1" class="form-control">
                            </div>
                            <div class="input-group input-group-outline my-3 px-4">
                                <label class="form-label" for="id_new_password2">Confirm Password</label>
                                <input type="password" name="new_password2" autocomplete="new-password" required
                                       id="id_new_password2" class="form-control">
                            </div>
                            <div class="input-group my-3 px-4">
                                <button type="submit" class="btn btn-primary px-4">Change Password</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>


{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <!-- Navbar -->
    <nav class="navbar navbar-main navbar-expand-lg px-0 mx-4 shadow-none border-radius-xl" id="navbarBlur"
         data-scroll="true">
        <div class="container-fluid py-1 px-3">
            <nav aria-label="breadcrumb">
                <img src="{% static 'img/logo.png' %}" class="navbar-brand-img h-100" width="150" alt="main_logo">

            </nav>
            <div class="collapse navbar-collapse mt-sm-0 mt-2 me-md-0 me-sm-4" id="navbar">
                <div class="ms-md-auto pe-md-3 d-flex align-items-center"></div>
                <ul class="navbar-nav  justify-content-end">
                    <li class="nav-item d-flex align-items-center text-dark">
                        <span class="d-sm-inline d-none text-xl"><span
                                class="text-success">Welcome!</span>&nbsp;{{ user.username }}</span>
                    </li>
                    &nbsp;&nbsp;<li class="nav-item dropdown pe-2 d-flex align-items-center">
                    <a href="javascript:" class="nav-link text-body p-0" id="dropdownMenuButton"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        <i class="fa fa-cog cursor-pointer"></i>
                    </a>
                    <ul class="dropdown-menu  dropdown-menu-end  px-2 py-3 me-sm-n4"
                        aria-labelledby="dropdownMenuButton">
                        <li class="mb-2">
                            <a class="dropdown-item border-radius-md" href="#"
                               onclick="showLoading(event, '{% url 'dashboard:change' %}')">
                                <div class="d-flex py-1">
                                    <div class="my-auto">
                                        <i class="fa fa-key" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;
                                    </div>
                                    <div class="d-flex flex-column justify-content-center">
                                        <h6 class="text-sm font-weight-normal mb-1">
                                            <span class="font-weight-bold text-warning">Change Password</span>
                                        </h6>
                                    </div>
                                </div>
                            </a>
                        </li>
                        <li class="mb-2">
                            <a class="dropdown-item border-radius-md" href="#"
                               onclick="showLoading(event, '{% url 'Logout' %}')">
                                <div class="d-flex py-1">
                                    <div class="my-auto">
                                        <i class="fa fa-sign-out" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;
                                    </div>
                                    <div class="d-flex flex-column justify-content-center">
                                        <h6 class="text-sm font-weight-normal mb-1">
                                            <span class="font-weight-bold text-danger">LogOut</span>
                                        </h6>
                                    </div>
                                </div>
                            </a>
                        </li>
                    </ul>
                </li>
                    <li class="nav-item d-xl-none ps-3 d-flex align-items-center">
                        <a href="javascript:" class="nav-link text-body p-0" id="iconNavbarSidenav">
                            <div class="sidenav-toggler-inner">
                                <i class="sidenav-toggler-line"></i>
                                <i class="sidenav-toggler-line"></i>
                                <i class="sidenav-toggler-line"></i>
                            </div>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <!-- End Navbar -->
    <div class="container-fluid py-4">
        <div class="row">
            <div class="col-xl-3 col-sm-6 mb-xl-0 mb-4">
                <div class="card">
                    <div class="card-header p-3 pt-2">
                        <div class="icon icon-lg icon-shape bg-gradient-success shadow-dark text-center border-radius-xl mt-n4 position-absolute">
                            <i class="material-icons opacity-10" style="font-size:35px;">mode_of_travel</i>
                        </div>
                        <div class="text-end pt-1">
                            <p class="text-xl mb-0 text-capitalize text-dark">Pending services request</p>
                            <h5 class="mb-0">{{ pservice }}</h5>
                        </div>
                    </div>
                    <hr class="horizontal my-0">
                    <div class="card-footer p-3">
                    </div>
                </div>
            </div>
            <div class="col-xl-3 col-sm-6 mb-xl-0 mb-4">
                <div class="card">
                    <div class="card-header p-3 pt-2">
                        <div class="icon icon-lg icon-shape bg-gradient-primary shadow-primary text-center border-radius-xl mt-n4 position-absolute">
                            <i class="material-icons opacity-10">person</i>
                        </div>
                        <div class="text-end pt-1">
                            <p class="text-xl mb-0 text-capitalize text-dark">Completed Service request</p>
                            <h5 class="mb-0">{{ tservice }}</h5>
                        </div>
                    </div>
                    <hr class="horizontal my-0">
                    <div class="card-footer p-3">
                    </div>
                </div>
            </div>
            <div class="col-xl-3 col-sm-6 mb-xl-0 mb-4">
                <div class="card">
                    <div class="card-header p-3 pt-2">
                        <div class="icon icon-lg icon-shape bg-gradient-success shadow-success text-center border-radius-xl mt-n4 position-absolute">
                            <i class="material-icons opacity-10">person</i>
                        </div>
                        <div class="text-end pt-1">
                            <p class="text-xl mb-0 text-capitalize text-dark">Total Pc</p>
                            <h5 class="mb-0">{{ pc }}</h5>
                        </div>
                    </div>
                    <hr class="horizontal my-0">
                    <div class="card-footer p-3">
                    </div>
                </div>
            </div>
            <div class="col-xl-3 col-sm-6">
                <div class="card">
                    <div class="card-header p-3 pt-2">
                        <div class="icon icon-lg icon-shape bg-gradient-info shadow-info text-center border-radius-xl mt-n4 position-absolute">
                            <i class="material-icons opacity-10">weekend</i>
                        </div>
                        <div class="text-end pt-1">
                            <p class="text-xl mb-0 text-capitalize text-dark">Total Printers</p>
                            <h5 class="mb-0">{{ printer }}</h5>
                        </div>
                    </div>
                    <hr class="horizontal my-0">
                    <div class="card-footer p-3">
                    </div>
                </div>
            </div>
        </div>
        <div class="row mt-4">
        </div>
        <div class="row">
            <div class="col-lg-12 col-md-10 mb-md-0 mb-4">
                <div class="card">
                    <div class="card-header pb-0">
                        <h5 class="text-center">Pending Service List</h5>
                    </div>
                    <div class="card-body px-0 pb-2">
                        <div class="table-responsive p-0" style="max-height: 600px; overflow-y: auto;">
                            <table class="table align-items-center text-center mb-0">
                                <thead>
                                <tr>
                                    <th class="text-uppercase text-dark text-xs font-weight-bolder">ID</th>
                                    <th class="text-uppercase text-dark text-xs font-weight-bolder">Issue</th>
                                    <th class="text-uppercase text-dark text-xs font-weight-bolder ps-2">Branch</th>
                                    <th class="text-uppercase text-dark text-xs font-weight-bolder">User</th>
                                    <th class="text-uppercase text-dark text-xs font-weight-bolder">Asset ID</th>

                                </tr>
                                </thead>
                                <tbody>
                                {% for a in service %}
                                    <tr>
                                        <td class="align-middle text-center text-sm">
                                            <span class="text-xs text-dark font-weight-bold">{{ forloop.counter }}</span>
                                        </td>
                                        <td class="align-middle text-center text-sm">
                                            <a class="font-weight-bold" href="#"
                                               onclick="showLoading(event, '{% url 'dashboard:edit_service' a.id %}')">
                                                <span class="text-xs text-dark font-weight-bold"> {{ a.issue }} </span>
                                            </a>
                                        </td>

                                        <td class="align-middle text-center text-sm">
                                            <span class="text-xs text-dark font-weight-bold"> {{ a.branch }} </span>
                                        </td>
                                        <td class="align-middle text-center text-sm">
                                            <span class="text-xs text-dark font-weight-bold"> {{ a.user }} </span>
                                        </td>

                                        <td class="align-middle text-center text-sm">
                                            <span class="text-xs text-dark font-weight-bold"> {{ a.pc }} </span>
                                        </td>
                                    </tr> {% endfor %} </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
{% endblock %}
{% block js %}
    <script>
        function showLoading(event, url) {
            // Prevent the default behavior of the hyperlink
            event.preventDefault();

            // Display the loading animation
            document.getElementById("loading").style.display = "block";

            // Redirect to the URL after a 1-second delay
            setTimeout(function () {
                window.location.href = url;
            }, 1000);
        }
    </script>
{% endblock %}

templates/login.html
{% extends 'login_base.html' %}
{% load static %}
{% block css %}
    <style>
        #loading {
            position: fixed;
            z-index: 9999;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            background-color: rgba(0, 0, 0, 0.5);
            display: flex;
            justify-content: center;
            align-items: center;
        }

        #loading img {
            width: 100px;
            height: 100px;
            object-fit: contain;
        }
    </style>
{% endblock css %}
{% block content %}
    <div class="page-header align-items-start min-vh-100"
         style="background-image: url('https://images.unsplash.com/photo-1497294815431-9365093b7331?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1950&q=80');">
        <span class="mask bg-gradient-dark opacity-6"></span>
        <div class="container my-auto">
            <div class="row">
                <div id="loading" style="display:none;">
                    <!-- your loading animation code here -->
                    <img src="{% static 'img/loading.gif' %}" alt="loading">
                </div>
                <div class="col-lg-4 col-md-8 col-12 mx-auto">
                    <div class="card z-index-0 fadeIn3 fadeInBottom">
                        <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
                            <div class="bg-gradient-info shadow-primary border-radius-lg py-3 pe-1">
                                <h4 class="text-white font-weight-bolder text-center mt-2 mb-0">Sign in</h4>
                            </div>
                        </div>
                        <div class="card-body">
                            <form action="" method="post" role="form" class="text-start">
                                {% csrf_token %}
                                <div class="input-group input-group-outline my-3">
                                    <label class="form-label" for="id_username">UserName</label>
                                    <input name="username" id="id_username" class="form-control" required>
                                </div>
                                <div class="input-group input-group-outline mb-3">
                                    <label class="form-label" for="id_password">Password</label>
                                    <input type="password" name="password" id="id_password" class="form-control">
                                </div>

                                <div class="text-center">
                                    <button type="submit" class="btn bg-gradient-info w-100 my-4 mb-2" value="Login">
                                        Log in
                                    </button>
                                </div>

                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
{% endblock %}
{% block js %}
    <script>
    $('form').submit(function (event) {
        event.preventDefault();
        $.ajax({
            url: '{% url 'Login' %}',
            type: 'POST',
            data: $('form').serialize(),
            success: function (response) {
                if (response.success) {
                    // Display success message using SweetAlert
                    Swal.fire({
                        icon: 'success',
                        title: 'Success',
                        text: response.message,
                        showConfirmButton: false,
                        timer: 1000
                    }).then(function () {
                        // Redirect to the afterlogin page
                        window.location.href = '{% url "afterlogin" %}';
                    });
                } else {
                    // Display error message using SweetAlert
                    Swal.fire({
                        icon: 'error',
                        title: 'Error',
                        text: response.message,
                        showConfirmButton: false,
                        timer: 1000
                    });
                }
            },
            error: function (xhr, status, error) {
                console.log(xhr.responseText);
                // Display error message using SweetAlert
                Swal.fire({
                    icon: 'error',
                    title: 'Error',
                    text: 'An error occurred. Please try again later.',
                    showConfirmButton: false,
                    timer: 1000
                });
            },
            complete: function() {
                // Hide the loading image
                $('#loading').hide();
            }
        });
    });

    $(document).ready(function () {
        $('form').submit(function () {
            // Show the loading image
            $('#loading').show();
        });
    });
</script>
{% endblock %}

templates/login_base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no, user-scalable=0">
    <title>SSS Dashboard</title>
    <!--     Fonts and icons     -->
    <link rel="stylesheet" type="text/css"
          href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,900|Roboto+Slab:400,700"/>

    <!-- Material Icons -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons+Round" rel="stylesheet">

    <!-- CSS Files -->
    <link id="pagestyle" href="{% static 'css/material-dashboard.css' %}" rel="stylesheet"/>
    <!-- Font Awesome Icons -->
    <script src="https://kit.fontawesome.com/4933fc35b1.js" crossorigin="anonymous"></script>
    <script src="{% static 'js/plugins/sweetalert2@11.js' %}"></script>
    {% block css %}{% endblock css %}
</head>
<body class="g-sidenav-show  bg-gray-200">
<main class="main-content  mt-0">
    {% block content %}

    {% endblock %}

    {% include 'include/login_foooter.html' %}
</main>
</body>
<!--   Core JS Files   -->
<script src="{% static 'js/core/popper.min.js' %}"></script>
<script src="{% static 'js/core/bootstrap.min.js' %}"></script>
<script src="{% static 'js/plugins/perfect-scrollbar.min.js' %}"></script>
<script src="{% static 'js/plugins/smooth-scrollbar.min.js' %}"></script>
<script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
{% block js %}{% endblock js %}

<script>
    var win = navigator.platform.indexOf('Win') > -1;
    if (win && document.querySelector('#sidenav-scrollbar')) {
        var options = {
            damping: '0.5'
        }
        Scrollbar.init(document.querySelector('#sidenav-scrollbar'), options);
    }
</script>
<!-- Github buttons -->
<script async defer src="https://buttons.github.io/buttons.js"></script>
<!-- Control Center for Material Dashboard: parallax effects, scripts for the example pages etc -->
<script src="{% static 'js/material-dashboard.js' %}"></script>

</html>