sss/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashboard/', include('dash.urls')),
    path('login/', views.login_user, name='Login'),
    path('logout/', views.logout_user, name='Logout'),
    path('afterlogin', views.afterlogin_view, name='afterlogin'),
    path('service/', views.customer_view, name='customer'),
    path('save', views.save, name='save')
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dash/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Admin(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    address = models.CharField(max_length=50, null=False, blank=False)
    is_Active = models.BooleanField(default=True)

    @property
    def get_name(self):
        return self.user.first_name + " " + self.user.last_name

    @property
    def get_instance(self):
        return self

    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name_plural = "Admin"

templates/signup/signup.html
{% extends 'login_base.html' %}
{% load static %}
{% block content %}
    <main class="main-content  mt-0">
        <section>
            <div class="page-header min-vh-100">
                <div class="container">
                    <div class="row">
                        <div class="col-6 d-lg-flex d-none h-100 my-auto pe-0 position-absolute top-0 start-0 text-center justify-content-center flex-column">
                            <div class="position-relative bg-gradient-primary h-100 m-3 px-7 border-radius-lg d-flex flex-column justify-content-center"
                                 style="background-image: url({% static 'illustrates/5098293.jpg' %}); background-size: cover;">
                            </div>
                        </div>
                        <div class="col-xl-4 col-lg-5 col-md-7 d-flex flex-column ms-auto me-auto ms-lg-auto me-lg-5">
                            <div class="card card-plain">
                                <div class="card-header">
                                    <h4 class="font-weight-bolder">Sign Up</h4>
                                    <p class="mb-0">Enter your email and password to register</p>
                                </div>
                                <div class="card-body">
                                    <form role="form" method="post" enctype="multipart/form-data">
                                        {% csrf_token %}
                                        <div class="input-group input-group-outline mb-3">
                                            <label class="form-label" for="id_first_name">First Name</label>
                                            <input class="form-control" type="text" name="first_name" maxlength="150"
                                                   id="id_first_name">
                                        </div>
                                        <div class="input-group input-group-outline mb-3">
                                            <label class="form-label" for="id_last_name">Last name</label>
                                            <input class="form-control" type="text" name="last_name" maxlength="150"
                                                   id="id_last_name">
                                        </div>
                                        <div class="input-group input-group-outline mb-3">
                                            <label class="form-label" for="id_username">username</label>
                                            <input class="form-control" type="text" name="username" maxlength="150"
                                                   required id="id_username">
                                        </div>
                                        <div class="input-group input-group-outline mb-3">
                                            <label class="form-label" for="id_password">Password</label>
                                            <input class="form-control" type="password" name="password" maxlength="128"
                                                   required id="id_password">
                                        </div>

                                        <div class="input-group input-group-outline mb-3">
                                            <label class="form-label" for="id_address">Address</label>
                                            <input class="form-control" type="text" name="address" maxlength="10"
                                                   required id="id_address">
                                        </div>


                                        <div class="text-center">
                                            <button type="submit"
                                                    class="btn btn-lg bg-gradient-primary btn-lg w-100 mt-4 mb-0">Sign
                                                Up
                                            </button>
                                        </div>
                                    </form>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </main>
{% endblock %}